### PR TITLE
Add ctrl+Return shortcut to mark item as complete

### PR DESCRIPTION
**Pull request by mcorteel**
This is really missing. I'm not sure if my PR actually works, but I guess that the change should look something like that.

### CODE REVIEW

**Comment by Zren** [comment]
Is this a standard shortcut for something else? It's not a shortcut in [Google Tasks](https://mail.google.com/tasks/canvas).

**Comment by mcorteel** [comment]
I don't know if it's standard or if that's the particular shortcut that should be set, but IMO there should really be a shortcut to mark an item as completed (it may also switch the completed status).
Google Tasks uses alt+Return.

**Comment by Zren** [comment]
I'll add a `|| "alt+Return"` conditional after the merge so it's familiar with google task users too. That should hold them off till I figure out a way to make configurable shortcuts.

**Comment by Zren** [comment]
Also made it toggle instead of just setting complete=true.

* https://github.com/Zren/plasma-applets/commit/700e599395fbb25ec4d4cf60e6451602608d977c
* https://github.com/Zren/plasma-applets/commit/0a5961697a059e1c44ef75089e11c6d8212e1e25

**Comment by mcorteel** [comment]
That's awesome, thank you!

**Pull request merged**
